title: Shashank Kelkar
# logo: "/profile.png?raw=true"
description: Test Automation Consultant
<br>
<br>
<a href="mailto:kelkar14@gmail.com">kelkar14@gmail.com </a>
<br>
<a href="https://www.linkedin.com/in/shashank-kelkar-28164a34">LinkedIn Profile </a>
<br>
<a href="https://github.com/shashank0442">GitHub</a>
theme: jekyll-theme-minimal
