title: Shashank Kelkar
logo: /assets/img/logo.png
description: Test Automation Consultant
<br>
<br>
<a href="mailto:kelkar14@gmail.com">kelkar14@gmail.com </a>
<br>
<a href="https://www.linkedin.com/in/shashank-kelkar-28164a34">LinkedIn Profile </a>
<br>
<a href="https://github.com/shashank0442">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
